title: List 44 - Marketing in emerging tech
email: hello@desk520.com
description: "As you will see, the SERP is so far dominated by new companies. Emerging outfits for emerging industry!"
baseurl: ""
url: "https://list-44-emerging-tech.onrender.com"
twitter_username: tradingfanbois
instagram_username:  bfx.referral.code
medium_username: cryptolounge

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
